### PR TITLE
Statue of Discord Attraction

### PR DESCRIPTION
**Pull request by Ind-E**
Statue of Discord Attraction
The spirit of chaos and disharmony found his way into the spire and will spice up your deck with some chaos.

Upon choosing to embrace the chaos, different chaotic effects will be randomly applied to the cards in your deck. Possible modifiers are:
- 40% chance for jumbled name (AnagramNameModifier)
- 20% chance for randomized card color (RandomColorModifier)
- 10% chance for randomized card size (RandomSizeModifier)
- 30% chance for nothing to happen

Also added .vscode to the gitignore

### CODE REVIEW

**Review by modargo — CHANGES_REQUESTED** [review]
This looks like an amusing attraction. The overall structure looks good, and I've made a few comments with suggested changes and one thing to test.

I took a look at the effects in game as well and they're amusing without making cards difficult to recognize, which is good. I could see people getting tired of some of it, but it won't stop anyone from finishing a run. Just means that in future runs they might decline the statue's offer.

**Comment by modargo** [comment]
One other change you can make as part of this -- add yourself to the author_list field in ModTheSpire.json, so you're part of the credits for the mod as a whole.

**Review by Ind-E — COMMENTED** [review]
Added the effect to show cards, changed the anagram modifier to not reroll into the same name, changed the color modifier to not reroll into the same color. Tested in chinese, everything worked fine. And added my name to the authors list.

**Comment by modargo** [comment]
Looks good. Congrats on making one of the first contributions to the mod!

**Pull request merged**
